apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iu9yehfss-nodejs 
  janus-idp.io/tekton: iu9yehfss-nodejs
  backstage.io/kubernetes-id: iu9yehfss-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iu9yehfss-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml