apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iu9yehfss-nodejs
  janus-idp.io/tekton: iu9yehfss-nodejs
  backstage.io/kubernetes-id: iu9yehfss-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iu9yehfss-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
